Feature/co 839 implement get delete
osu-mist/inventory-api pull request #3
Opened 2017-07-12 23:27 UTC by jaredkosanovic

2017-07-14 23:49 UTC, floppyears requested changes

2017-07-14 23:49 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +    public static Integer MAX_PAGE_SIZE = 10000
Should we have the Inventory Resource class overwrite this variable? I don't know that we want Oracle returning 10K results at once.

2017-07-14 23:49 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/inventory/mapper/InventoryMapper.groovy
> +                        ZonedDateTime.parse(rs.getString("CREATED_AT"), dbFormatter) : null,
How about moving this to a function? It can then be reused by line 23 and 24 as well as unit tested?

2017-07-14 23:49 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/inventory/resources/InventoryResource.groovy
> +            try {
Hmm, we should probably start a transaction at the beginning of this method or a transaction that wraps around the call to deleteInventory(). My thinking is that if deleting some records fail, we don't end up with a half valid record.

2017-07-17 17:12 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +    public static Integer MAX_PAGE_SIZE = 10000
As we discussed, the queries aren't considering pagination and page[size] is being ignored.

2017-07-17 22:46 UTC, floppyears approved these changes

2017-07-17 22:46 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/inventory/resources/InventoryResource.groovy
> +                inventoryID, endpointUri
Does the endpointUri change per request? I'm wondering if the endpiontUri should be something that you pass to the constructor of iventoryDAOWrapper.

2017-07-18 15:40 UTC, merged